Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -59,8 +59,7 @@ jobs:
 
       - name: Extract Helm Chart
         run: |
-          mkdir helm-chart
-          tar -xzf helm-test-chart-0.1.0.tgz -C helm-chart || echo "Error extracting the Helm chart."
+          tar -xzf helm-test-chart-0.1.0.tgz || echo "Error extracting the Helm chart."
 
       - name: Install Helm
         run: |
@@ -71,7 +70,7 @@ jobs:
         env:
           IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
         run: |
-          helm package helm-chart/helm-test-chart --version "0.1.0-${{ env.commit_hash }}" --app-version "0.1.0-${{ env.commit_hash }}"
+          helm package helm-test-chart --version "0.1.0-${{ env.commit_hash }}" --app-version "0.1.0-${{ env.commit_hash }}"
 
       - name: Push Helm Chart to ECR as OCI
         env:
@@ -79,7 +78,7 @@ jobs:
           IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
         run: |
           echo $(aws ecr get-login-password --region ${{ env.AWS_REGION }}) | helm registry login -u AWS --password-stdin $ECR_REGISTRY
-          helm chart save helm-chart/helm-test-chart-0.1.0-${{ env.commit_hash }}.tgz oci://$ECR_REGISTRY/$ECR_HELM_REPOSITORY
+          helm chart save helm-test-chart-0.1.0-${{ env.commit_hash }}.tgz oci://$ECR_REGISTRY/$ECR_HELM_REPOSITORY
           helm chart push oci://$ECR_REGISTRY/$ECR_HELM_REPOSITORY
 
       - name: Update values.yaml with New Image Tag
