Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -14,9 +14,9 @@ env:
   ECR_REPOSITORY: nexus-repo
   AWS_REGION: eu-west-1
   VALUES_FILE: nexus-application/values.yaml
-  OTHER_REPO: coforge-nexus/helmcharts  # Target repository
-  HELM_CHART_DIR: helm-test-chart  # Directory of your Helm chart
-  HELM_ECR_REPOSITORY: 442426854264.dkr.ecr.eu-west-1.amazonaws.com/helm-test-chart  # ECR URI for Helm
+  OTHER_REPO: coforge-nexus/helmcharts
+  HELM_CHART_DIR: helm-test-chart  # <-- Define the Helm chart directory here
+  HELM_ECR_REPOSITORY: 442426854264.dkr.ecr.eu-west-1.amazonaws.com/helm-test-chart
 
 jobs:
   update-deployment:
@@ -59,26 +59,29 @@ jobs:
           IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
           MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
         run: |
-          # Checkout the other repository with the token
           git clone https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git other-repo
           cd other-repo
           
-          # Update the values.yaml file with the new image
           sed -i "s|repository: .*|repository: $ECR_REGISTRY/$ECR_REPOSITORY|" ${{ env.VALUES_FILE }}
           sed -i "s|tag: .*|tag: $IMAGE_TAG|" ${{ env.VALUES_FILE }}
 
-          # Commit the changes
           git config --local user.email "Gandam.manikantha@coforge.com"
           git config --local user.name "Ubhaskar-coforge"
           git add ${{ env.VALUES_FILE }}
           git commit -m "Update values.yaml with new image tag $IMAGE_TAG"
 
-          # Push the changes using the token
           git push https://$MY_GITHUB_PAT:x-oauth-basic@github.com/${{ env.OTHER_REPO }}.git
 
       - name: Install Helm
         run: |
           curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+
+      - name: Verify Helm Chart Directory
+        run: |
+          if [ ! -d "${{ env.HELM_CHART_DIR }}" ]; then
+            echo "Helm chart directory ${{ env.HELM_CHART_DIR }} not found."
+            exit 1
+          fi
 
       - name: Log in to ECR for Helm
         env:
